// Invoice normalizer — the "ambiguous input" front door.
//
// Real invoices arrive as messy JSON: alternate key spellings, amounts as
// strings with currency symbols and thousands separators, missing fields, and
// line items that may or may not sum to the stated total. This module coerces a
// RawInvoice into a NormalizedInvoice with nullable fields, filling gaps where it
// safely can and recording every coercion/inference in `notes` so a reviewer sees
// exactly how messy the source was. It never throws — a totally empty payload
// still yields a NormalizedInvoice (with an id) that validation can flag.

import { randomUUID } from "node:crypto";
import type { LineItem, NormalizedInvoice, RawInvoice } from "../types.js";
import { isSupportedCurrency } from "./currency.js";

// Accepted aliases for each canonical field. Every present alias is reconciled;
// conflicting values become explicit ambiguity rather than a first-key winner.
const ALIASES: Record<string, string[]> = {
  invoice_id: ["invoice_id", "id", "invoiceId"],
  vendor: ["vendor", "supplier", "vendor_name", "supplier_name", "from", "payee"],
  vendor_ref: ["vendor_ref", "invoice_number", "invoiceNo", "invoice_no", "number", "ref", "reference"],
  invoice_date: ["invoice_date", "date", "issued", "issue_date", "issued_at"],
  currency: ["currency", "ccy"],
  subtotal: ["subtotal", "net", "net_amount", "amount_excl_tax", "pre_tax"],
  tax: ["tax", "tax_amount", "vat", "vat_amount", "tax_total"],
  tax_id: ["tax_id", "tax_number", "tax_reg", "vendor_tax_id", "registration"],
  total: ["total", "amount", "grand_total", "amount_due", "gross", "total_amount"],
};

export function normalizeInvoice(raw: RawInvoice): NormalizedInvoice {
  const notes: string[] = [];
  const ambiguousAmounts = new Set<string>();
  const src = raw ?? {};

  // Never trust a caller to choose our correlation/idempotency key. A supplied
  // invoice_id is business data, so it may fill vendor_ref, while the internal id
  // is always a full server-generated UUID.
  const suppliedInvoiceIdResult = resolveStringAliases(
    src,
    ALIASES.invoice_id!,
    "caller invoice_id",
    notes,
    canonicalReference
  );
  const suppliedInvoiceId = suppliedInvoiceIdResult.value;
  const invoice_id = `inv-${randomUUID()}`;
  notes.push("internal invoice_id generated by the server");

  const vendor = resolveStringAliases(
    src,
    ALIASES.vendor!,
    "vendor",
    notes,
    canonicalVendorKey
  ).value;
  if (!vendor) notes.push("vendor name missing");

  const vendorRefResult = resolveStringAliases(
    src,
    ALIASES.vendor_ref!,
    "vendor_ref",
    notes,
    canonicalReference
  );
  const vendor_ref = vendorRefResult.conflicted ? null : vendorRefResult.value ?? suppliedInvoiceId;
  if (!vendor_ref) notes.push("vendor invoice number (vendor_ref) missing");
  if (suppliedInvoiceId) {
    notes.push(
      vendor_ref === suppliedInvoiceId
        ? "caller-supplied invoice_id treated as the external vendor_ref"
        : "caller-supplied invoice_id ignored as an internal id (vendor_ref was supplied separately)"
    );
  }

  const invoice_date = resolveDateAliases(src, ALIASES.invoice_date!, notes);

  const declaredCurrencyResult = resolveStringAliases(
    src,
    ALIASES.currency!,
    "currency",
    notes,
    (value) => value.toUpperCase()
  );
  const currency = declaredCurrencyResult.conflicted
    ? "UNKNOWN"
    : resolveCurrency(declaredCurrencyResult.value, src, notes);

  const subtotal = resolveAmountAliases(src, ALIASES.subtotal!, "subtotal", notes, ambiguousAmounts);
  const tax = resolveAmountAliases(src, ALIASES.tax!, "tax", notes, ambiguousAmounts);
  const tax_id = resolveStringAliases(
    src,
    ALIASES.tax_id!,
    "tax_id",
    notes,
    (value) => value.normalize("NFKC").toUpperCase().replace(/\s+/g, "")
  ).value;
  if (!tax_id) notes.push("vendor tax_id missing");
  let total = resolveAmountAliases(src, ALIASES.total!, "total", notes, ambiguousAmounts);

  const line_items = normalizeLineItems(src["line_items"] ?? src["lines"] ?? src["items"], notes);
  const confidence = parseConfidence(src["confidence"]);
  const extraction_confidence =
    confidence != null && confidence >= 0 && confidence <= 1 ? confidence : null;
  if (confidence != null && extraction_confidence == null) {
    notes.push(`extraction confidence ${confidence} was outside 0..1 and ignored`);
  }

  // If total is absent but subtotal + tax are present, infer it (and note it).
  if (total == null && !ambiguousAmounts.has("total") && subtotal != null && tax != null) {
    total = round2(subtotal + tax);
    notes.push(`total inferred from subtotal + tax = ${total}`);
  }
  // If subtotal is absent but total + tax are present, infer it.
  let sub = subtotal;
  if (sub == null && !ambiguousAmounts.has("subtotal") && total != null && tax != null) {
    sub = round2(total - tax);
    notes.push(`subtotal inferred from total - tax = ${sub}`);
  }

  return {
    invoice_id,
    vendor,
    vendor_ref,
    invoice_date,
    currency,
    subtotal: sub,
    tax,
    tax_id,
    total,
    line_items,
    extraction_confidence,
    notes,
    raw: src,
  };
}

interface AliasResolution<T> {
  value: T | null;
  conflicted: boolean;
}

function resolveStringAliases(
  src: RawInvoice,
  keys: string[],
  label: string,
  notes: string[],
  canonicalize: (value: string) => string = (value) =>
    value.normalize("NFKC").trim().replace(/\s+/g, " ").toLowerCase()
): AliasResolution<string> {
  const present: Array<{ key: string; value: string; canonical: string }> = [];
  for (const key of keys) {
    const raw = src[key];
    const value =
      typeof raw === "string" && raw.trim()
        ? raw.trim()
        : typeof raw === "number" && Number.isFinite(raw)
          ? String(raw)
          : null;
    if (value == null) continue;
    present.push({ key, value, canonical: canonicalize(value) });
  }
  if (present.length === 0) return { value: null, conflicted: false };
  if (new Set(present.map((entry) => entry.canonical)).size > 1) {
    notes.push(
      `conflicting aliases for ${label} (${present.map((entry) => entry.key).join(", ")}) — marked missing/ambiguous`
    );
    return { value: null, conflicted: true };
  }
  return { value: present[0]!.value, conflicted: false };
}

// Parse an amount that may arrive as a number, or a string like "€1,234.50",
// "1.234,50" (EU grouping), or "USD 900". Returns null when unparseable.
export function parseAmount(value: unknown): number | null {
  if (typeof value === "number") return Number.isFinite(value) ? value : null;
  if (typeof value !== "string") return null;
  const raw = value.trim();
  const parenthesizedNegative = /^\(.*\)$/.test(raw);
  let s = raw.replace(/[\s\u00a0'_]/g, "").replace(/[^\d.,-]/g, "");
  if (s === "" || s === "-" || (s.match(/-/g)?.length ?? 0) > 1) return null;
  s = s.replace(/^-/, "");
  const lastComma = s.lastIndexOf(",");
  const lastDot = s.lastIndexOf(".");
  if (lastComma >= 0 && lastDot >= 0) {
    // When both occur, the right-most separator is the decimal mark and the
    // other must form regular three-digit groups. Reject mixed/irregular strings
    // rather than silently changing their order of magnitude.
    const decimal = lastComma > lastDot ? "," : ".";
    const grouping = decimal === "," ? "." : ",";
    if (countChar(s, decimal) !== 1) return null;
    const splitAt = s.lastIndexOf(decimal);
    const integer = s.slice(0, splitAt);
    const fraction = s.slice(splitAt + 1);
    if (!/^\d+$/.test(fraction) || !validGroupedInteger(integer, grouping)) return null;
    s = integer.split(grouping).join("") + "." + fraction;
  } else if (lastComma >= 0 || lastDot >= 0) {
    const separator = lastComma >= 0 ? "," : ".";
    const parts = s.split(separator);
    if (parts.some((p, i) => p === "" && i !== 0)) return null;
    if (parts.length > 2) {
      if (!validGroupedInteger(s, separator)) return null;
      s = parts.join("");
    } else {
      const [integer, fraction] = parts as [string, string];
      // A leading zero makes the intent unambiguously fractional: 0.123 is
      // 0.123, not 123. Otherwise preserve the common invoice convention where
      // a lone three-digit tail is a grouping mark (1,234 / 1.234).
      const leadingZeroDecimal = /^0+$/.test(integer);
      if (!leadingZeroDecimal && integer.length >= 1 && fraction.length === 3) return null;
      s = `${integer || "0"}.${fraction}`;
    }
  }
  const n = Number(s) * (parenthesizedNegative || /^\s*-/.test(raw) ? -1 : 1);
  return Number.isFinite(n) ? n : null;
}

function countChar(value: string, char: string): number {
  return value.split(char).length - 1;
}

function validGroupedInteger(value: string, separator: string): boolean {
  const escaped = separator === "." ? "\\." : separator;
  return new RegExp(`^\\d{1,3}(?:${escaped}\\d{3})+$`).test(value);
}

// Stable keys for deterministic duplicate lookup. Deliberately conservative:
// case/Unicode/whitespace differences collapse, but legal-name suffixes and
// punctuation do not, avoiding accidental cross-vendor merges.
export function canonicalVendorKey(value: string | null | undefined): string {
  return (value ?? "").normalize("NFKC").trim().replace(/\s+/g, " ").toLocaleLowerCase("en-US");
}

export function canonicalReference(value: string | null | undefined): string {
  return (value ?? "").normalize("NFKC").trim().replace(/\s+/g, " ").toLocaleUpperCase("en-US");
}

function currencyEvidence(src: RawInvoice): { explicitCodes: Set<string>; symbols: Set<string> } {
  const explicitCodes = new Set<string>();
  const symbols = new Set<string>();
  for (const key of [...ALIASES.total!, ...ALIASES.subtotal!, ...ALIASES.tax!]) {
    const value = src[key];
    if (typeof value !== "string") continue;
    const upper = value.toUpperCase();
    for (const match of upper.matchAll(/(^|[^A-Z])([A-Z]{3})(?=[^A-Z]|$)/g)) {
      const code = match[2]!;
      if (isSupportedCurrency(code)) explicitCodes.add(code);
    }
    for (const symbol of ["€", "£", "¥", "$"]) {
      if (value.includes(symbol)) symbols.add(symbol);
    }
  }
  return { explicitCodes, symbols };
}

const SYMBOL_COMPATIBILITY: Record<string, readonly string[]> = {
  "€": ["EUR"],
  "£": ["GBP"],
  // These symbols are intrinsically ambiguous without a compatible ISO code.
  "$": ["USD", "CAD", "AUD"],
  "¥": ["JPY", "CNY"],
};

function symbolsCompatible(code: string, symbols: Set<string>): boolean {
  return [...symbols].every((symbol) => SYMBOL_COMPATIBILITY[symbol]?.includes(code));
}

function resolveCurrency(declared: string | null, src: RawInvoice, notes: string[]): string {
  const { explicitCodes, symbols } = currencyEvidence(src);
  if (declared) {
    const code = declared.toUpperCase();
    if (!isSupportedCurrency(code)) {
      notes.push(`currency ${JSON.stringify(declared)} is not a supported ISO 4217 code — marked UNKNOWN`);
      return "UNKNOWN";
    }
    // A declared ISO code and an explicit ISO code printed beside an amount are
    // equally strong evidence. If they disagree, guessing could create a payment
    // in the wrong currency, so preserve the ambiguity for human clarification.
    if (explicitCodes.size > 0 && (explicitCodes.size > 1 || !explicitCodes.has(code))) {
      notes.push(
        `conflicting explicit currency codes (${[code, ...explicitCodes].filter((v, i, a) => a.indexOf(v) === i).join(", ")}) — marked UNKNOWN`
      );
      return "UNKNOWN";
    }
    if (!symbolsCompatible(code, symbols)) {
      notes.push(
        `declared currency ${code} conflicts with amount symbol(s) ${[...symbols].join(", ")} — marked UNKNOWN`
      );
      return "UNKNOWN";
    }
    return code;
  }
  return inferCurrency(src, notes) ?? "UNKNOWN";
}

function inferCurrency(src: RawInvoice, notes: string[]): string | null {
  const { explicitCodes, symbols } = currencyEvidence(src);

  // An ISO code is stronger than a symbol: "$" is used for USD, CAD and AUD.
  // Thus "CAD $1,000" is CAD, not a fabricated CAD/USD conflict.
  if (explicitCodes.size === 1) {
    const currency = [...explicitCodes][0]!;
    if (!symbolsCompatible(currency, symbols)) {
      notes.push(
        `explicit currency ${currency} conflicts with amount symbol(s) ${[...symbols].join(", ")} — marked UNKNOWN`
      );
      return null;
    }
    notes.push(`currency inferred from explicit ISO code as ${currency}`);
    return currency;
  }
  if (explicitCodes.size > 1) {
    notes.push(`conflicting explicit currency codes (${[...explicitCodes].join(", ")}) — marked UNKNOWN`);
    return null;
  }
  if (symbols.size === 1) {
    const symbol = [...symbols][0]!;
    const compatible = SYMBOL_COMPATIBILITY[symbol] ?? [];
    if (compatible.length === 1) {
      const currency = compatible[0]!;
      notes.push(`currency inferred from unambiguous amount symbol as ${currency}`);
      return currency;
    }
    notes.push(`currency symbol ${symbol} is ambiguous without an ISO code — marked UNKNOWN`);
    return null;
  }
  if (symbols.size > 1) {
    notes.push(`conflicting currency symbols (${[...symbols].join(", ")}) — marked UNKNOWN`);
    return null;
  }
  notes.push("currency missing — marked UNKNOWN for human clarification");
  return null;
}

function resolveAmountAliases(
  src: RawInvoice,
  keys: string[],
  label: string,
  notes: string[],
  ambiguous?: Set<string>
): number | null {
  const present: Array<{ key: string; amount: number }> = [];
  let invalid = false;
  for (const k of keys) {
    if (!(k in src)) continue;
    const raw = src[k];
    if (raw == null || raw === "") continue;
    const n = parseAmount(raw);
    if (n != null) {
      if (typeof raw === "string") notes.push(`${label} "${raw}" parsed as ${n}`);
      present.push({ key: k, amount: round2(n) });
      continue;
    }
    invalid = true;
    notes.push(`${label} alias ${k} was unparseable`);
  }
  if (present.length === 0) {
    if (invalid) ambiguous?.add(label);
    return null;
  }
  const first = present[0]!.amount;
  if (invalid || present.some((entry) => Math.abs(entry.amount - first) > 0.01)) {
    ambiguous?.add(label);
    notes.push(
      `conflicting aliases for ${label} (${present.map((entry) => entry.key).join(", ")}) — marked missing/ambiguous`
    );
    return null;
  }
  return first;
}

function parseConfidence(value: unknown): number | null {
  if (typeof value === "number") return Number.isFinite(value) ? value : null;
  if (typeof value !== "string") return null;
  const text = value.trim();
  if (!/^[+-]?(?:\d+(?:\.\d+)?|\.\d+)$/.test(text)) return null;
  const parsed = Number(text);
  return Number.isFinite(parsed) ? parsed : null;
}

function resolveDateAliases(src: RawInvoice, keys: string[], notes: string[]): string | null {
  const values: Array<{ key: string; normalized: string | null }> = [];
  for (const key of keys) {
    const raw = src[key];
    const value =
      typeof raw === "string" && raw.trim()
        ? raw.trim()
        : typeof raw === "number" && Number.isFinite(raw)
          ? String(raw)
          : null;
    if (value == null) continue;
    values.push({ key, normalized: normalizeDate(value, notes) });
  }
  if (values.length === 0) return null;
  const valid = values
    .map((entry) => entry.normalized)
    .filter((value): value is string => value != null);
  if (valid.length !== values.length || new Set(valid).size > 1) {
    notes.push(
      `conflicting aliases for invoice_date (${values.map((entry) => entry.key).join(", ")}) — marked missing/ambiguous`
    );
    return null;
  }
  return valid[0] ?? null;
}

function normalizeDate(value: string | null, notes: string[]): string | null {
  if (!value) return null;
  const text = value.trim();
  // Numeric day/month strings are locale-dependent (03/04 can mean two dates).
  // Never let the host runtime's locale guess turn one into a payable due fact.
  if (/^\d{1,2}[/.]\d{1,2}[/.]\d{2,4}$/.test(text)) {
    notes.push(`invoice_date "${value}" is locale-ambiguous — marked missing`);
    return null;
  }

  const iso = /^(\d{4})-(\d{2})-(\d{2})(?:T.*)?$/.exec(text);
  if (iso) {
    const y = Number(iso[1]);
    const m = Number(iso[2]);
    const d = Number(iso[3]);
    if (validCalendarDate(y, m, d) && (!text.includes("T") || Number.isFinite(Date.parse(text)))) {
      return `${iso[1]}-${iso[2]}-${iso[3]}`;
    }
    notes.push(`invoice_date "${value}" was unparseable`);
    return null;
  }

  const monthFirst = /^([A-Za-z]{3,9})\s+(\d{1,2}),?\s+(\d{4})$/.exec(text);
  const dayFirst = /^(\d{1,2})\s+([A-Za-z]{3,9})\s+(\d{4})$/.exec(text);
  const parts = monthFirst
    ? { day: Number(monthFirst[2]), month: monthNumber(monthFirst[1]!), year: Number(monthFirst[3]) }
    : dayFirst
      ? { day: Number(dayFirst[1]), month: monthNumber(dayFirst[2]!), year: Number(dayFirst[3]) }
      : null;
  if (parts?.month && validCalendarDate(parts.year, parts.month, parts.day)) {
    return `${String(parts.year).padStart(4, "0")}-${String(parts.month).padStart(2, "0")}-${String(parts.day).padStart(2, "0")}`;
  }
  notes.push(`invoice_date "${value}" was unparseable`);
  return null;
}

function validCalendarDate(year: number, month: number, day: number): boolean {
  if (!Number.isInteger(year) || !Number.isInteger(month) || !Number.isInteger(day)) return false;
  const date = new Date(Date.UTC(year, month - 1, day));
  return date.getUTCFullYear() === year && date.getUTCMonth() === month - 1 && date.getUTCDate() === day;
}

function monthNumber(value: string): number | null {
  const key = value.slice(0, 3).toLowerCase();
  const months: Record<string, number> = {
    jan: 1, feb: 2, mar: 3, apr: 4, may: 5, jun: 6,
    jul: 7, aug: 8, sep: 9, oct: 10, nov: 11, dec: 12,
  };
  return months[key] ?? null;
}

function normalizeLineItems(value: unknown, notes: string[]): LineItem[] {
  if (!Array.isArray(value)) return [];
  const items: LineItem[] = [];
  for (const [index, entry] of value.entries()) {
    if (typeof entry !== "object" || entry == null) continue;
    const e = entry as Record<string, unknown>;
    items.push({
      description: resolveStringAliases(
        e,
        ["description", "desc", "name", "item"],
        `line_items[${index}].description`,
        notes
      ).value ?? "(no description)",
      quantity: resolveAmountAliases(e, ["quantity", "qty"], `line_items[${index}].quantity`, notes),
      unit_price: resolveAmountAliases(e, ["unit_price", "price", "rate"], `line_items[${index}].unit_price`, notes),
      amount: resolveAmountAliases(e, ["amount", "total", "line_total"], `line_items[${index}].amount`, notes),
    });
  }
  if (items.length === 0 && value.length > 0) {
    notes.push("line_items present but none were parseable");
  }
  return items;
}

function round2(n: number): number {
  return Math.round(n * 100) / 100;
}
