// Invoice normalizer — the "ambiguous input" front door.
//
// Real invoices arrive as messy JSON: alternate key spellings, amounts as
// strings with currency symbols and thousands separators, missing fields, and
// line items that may or may not sum to the stated total. This module coerces a
// RawInvoice into a NormalizedInvoice with nullable fields, filling gaps where it
// safely can and recording every coercion/inference in `notes` so a reviewer sees
// exactly how messy the source was. It never throws — a totally empty payload
// still yields a NormalizedInvoice (with an id) that validation can flag.

import { randomUUID } from "node:crypto";
import type { LineItem, NormalizedInvoice, RawInvoice } from "../types.js";

// Accepted aliases for each canonical field. First present, non-empty wins.
const ALIASES: Record<string, string[]> = {
  invoice_id: ["invoice_id", "id", "invoiceId"],
  vendor: ["vendor", "supplier", "vendor_name", "supplier_name", "from", "payee"],
  vendor_ref: ["vendor_ref", "invoice_number", "invoiceNo", "invoice_no", "number", "ref", "reference"],
  invoice_date: ["invoice_date", "date", "issued", "issue_date", "issued_at"],
  currency: ["currency", "ccy"],
  subtotal: ["subtotal", "net", "net_amount", "amount_excl_tax", "pre_tax"],
  tax: ["tax", "tax_amount", "vat", "vat_amount", "tax_total"],
  tax_id: ["tax_id", "tax_number", "tax_reg", "vendor_tax_id", "registration"],
  total: ["total", "amount", "grand_total", "amount_due", "gross", "total_amount"],
};

export function normalizeInvoice(raw: RawInvoice): NormalizedInvoice {
  const notes: string[] = [];
  const src = raw ?? {};

  // Never trust a caller to choose our correlation/idempotency key. A supplied
  // invoice_id is business data, so it may fill vendor_ref, while the internal id
  // is always a full server-generated UUID.
  const suppliedInvoiceId = pickString(src, ALIASES.invoice_id!);
  const invoice_id = `inv-${randomUUID()}`;
  notes.push("internal invoice_id generated by the server");

  const vendor = pickString(src, ALIASES.vendor!);
  if (!vendor) notes.push("vendor name missing");

  const vendor_ref = pickString(src, ALIASES.vendor_ref!) ?? suppliedInvoiceId;
  if (!vendor_ref) notes.push("vendor invoice number (vendor_ref) missing");
  if (suppliedInvoiceId) {
    notes.push(
      vendor_ref === suppliedInvoiceId
        ? "caller-supplied invoice_id treated as the external vendor_ref"
        : "caller-supplied invoice_id ignored as an internal id (vendor_ref was supplied separately)"
    );
  }

  const invoice_date = normalizeDate(pickString(src, ALIASES.invoice_date!), notes);

  const declaredCurrency = pickString(src, ALIASES.currency!);
  const currency = resolveCurrency(declaredCurrency, src, notes);

  const subtotal = pickAmount(src, ALIASES.subtotal!, "subtotal", notes);
  const tax = pickAmount(src, ALIASES.tax!, "tax", notes);
  const tax_id = pickString(src, ALIASES.tax_id!);
  if (!tax_id) notes.push("vendor tax_id missing");
  let total = pickAmount(src, ALIASES.total!, "total", notes);

  const line_items = normalizeLineItems(src["line_items"] ?? src["lines"] ?? src["items"], notes);
  const confidence = parseAmount(src["confidence"]);
  const extraction_confidence =
    confidence != null && confidence >= 0 && confidence <= 1 ? confidence : null;
  if (confidence != null && extraction_confidence == null) {
    notes.push(`extraction confidence ${confidence} was outside 0..1 and ignored`);
  }

  // If total is absent but subtotal + tax are present, infer it (and note it).
  if (total == null && subtotal != null && tax != null) {
    total = round2(subtotal + tax);
    notes.push(`total inferred from subtotal + tax = ${total}`);
  }
  // If subtotal is absent but total + tax are present, infer it.
  let sub = subtotal;
  if (sub == null && total != null && tax != null) {
    sub = round2(total - tax);
    notes.push(`subtotal inferred from total - tax = ${sub}`);
  }

  return {
    invoice_id,
    vendor,
    vendor_ref,
    invoice_date,
    currency,
    subtotal: sub,
    tax,
    tax_id,
    total,
    line_items,
    extraction_confidence,
    notes,
    raw: src,
  };
}

function pickString(src: RawInvoice, keys: string[]): string | null {
  for (const k of keys) {
    const v = src[k];
    if (typeof v === "string" && v.trim().length > 0) return v.trim();
    if (typeof v === "number" && Number.isFinite(v)) return String(v);
  }
  return null;
}

// Parse an amount that may arrive as a number, or a string like "€1,234.50",
// "1.234,50" (EU grouping), or "USD 900". Returns null when unparseable.
export function parseAmount(value: unknown): number | null {
  if (typeof value === "number") return Number.isFinite(value) ? value : null;
  if (typeof value !== "string") return null;
  const raw = value.trim();
  const parenthesizedNegative = /^\(.*\)$/.test(raw);
  let s = raw.replace(/[\s\u00a0'_]/g, "").replace(/[^\d.,-]/g, "");
  if (s === "" || s === "-" || (s.match(/-/g)?.length ?? 0) > 1) return null;
  s = s.replace(/^-/, "");
  const lastComma = s.lastIndexOf(",");
  const lastDot = s.lastIndexOf(".");
  if (lastComma >= 0 && lastDot >= 0) {
    // When both occur, the right-most separator is the decimal mark and the
    // other must form regular three-digit groups. Reject mixed/irregular strings
    // rather than silently changing their order of magnitude.
    const decimal = lastComma > lastDot ? "," : ".";
    const grouping = decimal === "," ? "." : ",";
    if (countChar(s, decimal) !== 1) return null;
    const splitAt = s.lastIndexOf(decimal);
    const integer = s.slice(0, splitAt);
    const fraction = s.slice(splitAt + 1);
    if (!/^\d+$/.test(fraction) || !validGroupedInteger(integer, grouping)) return null;
    s = integer.split(grouping).join("") + "." + fraction;
  } else if (lastComma >= 0 || lastDot >= 0) {
    const separator = lastComma >= 0 ? "," : ".";
    const parts = s.split(separator);
    if (parts.some((p, i) => p === "" && i !== 0)) return null;
    if (parts.length > 2) {
      if (!validGroupedInteger(s, separator)) return null;
      s = parts.join("");
    } else {
      const [integer, fraction] = parts as [string, string];
      // A leading zero makes the intent unambiguously fractional: 0.123 is
      // 0.123, not 123. Otherwise preserve the common invoice convention where
      // a lone three-digit tail is a grouping mark (1,234 / 1.234).
      const leadingZeroDecimal = /^0+$/.test(integer);
      const grouping = !leadingZeroDecimal && integer.length >= 1 && fraction.length === 3;
      s = grouping ? integer + fraction : `${integer || "0"}.${fraction}`;
    }
  }
  const n = Number(s) * (parenthesizedNegative || /^\s*-/.test(raw) ? -1 : 1);
  return Number.isFinite(n) ? n : null;
}

function countChar(value: string, char: string): number {
  return value.split(char).length - 1;
}

function validGroupedInteger(value: string, separator: string): boolean {
  const escaped = separator === "." ? "\\." : separator;
  return new RegExp(`^\\d{1,3}(?:${escaped}\\d{3})+$`).test(value);
}

// Stable keys for deterministic duplicate lookup. Deliberately conservative:
// case/Unicode/whitespace differences collapse, but legal-name suffixes and
// punctuation do not, avoiding accidental cross-vendor merges.
export function canonicalVendorKey(value: string | null | undefined): string {
  return (value ?? "").normalize("NFKC").trim().replace(/\s+/g, " ").toLocaleLowerCase("en-US");
}

export function canonicalReference(value: string | null | undefined): string {
  return (value ?? "").normalize("NFKC").trim().replace(/\s+/g, " ").toLocaleUpperCase("en-US");
}

function currencyEvidence(src: RawInvoice): { explicitCodes: Set<string>; symbolCodes: Set<string> } {
  const explicitCodes = new Set<string>();
  const symbolCodes = new Set<string>();
  for (const key of [...ALIASES.total!, ...ALIASES.subtotal!, ...ALIASES.tax!]) {
    const value = src[key];
    if (typeof value !== "string") continue;
    const upper = value.toUpperCase();
    for (const code of ["EUR", "USD", "GBP", "JPY", "CHF", "CAD", "AUD"]) {
      if (new RegExp(`(^|[^A-Z])${code}([^A-Z]|$)`).test(upper)) explicitCodes.add(code);
    }
    if (value.includes("€")) symbolCodes.add("EUR");
    if (value.includes("£")) symbolCodes.add("GBP");
    if (value.includes("¥")) symbolCodes.add("JPY");
    if (value.includes("$")) symbolCodes.add("USD");
  }
  return { explicitCodes, symbolCodes };
}

function resolveCurrency(declared: string | null, src: RawInvoice, notes: string[]): string {
  const { explicitCodes } = currencyEvidence(src);
  if (declared) {
    const code = declared.toUpperCase();
    if (!/^[A-Z]{3}$/.test(code)) {
      notes.push(`currency ${JSON.stringify(declared)} is not a 3-letter ISO code — marked UNKNOWN`);
      return "UNKNOWN";
    }
    // A declared ISO code and an explicit ISO code printed beside an amount are
    // equally strong evidence. If they disagree, guessing could create a payment
    // in the wrong currency, so preserve the ambiguity for human clarification.
    if (explicitCodes.size > 0 && (explicitCodes.size > 1 || !explicitCodes.has(code))) {
      notes.push(
        `conflicting explicit currency codes (${[code, ...explicitCodes].filter((v, i, a) => a.indexOf(v) === i).join(", ")}) — marked UNKNOWN`
      );
      return "UNKNOWN";
    }
    return code;
  }
  return inferCurrency(src, notes) ?? "UNKNOWN";
}

function inferCurrency(src: RawInvoice, notes: string[]): string | null {
  const { explicitCodes, symbolCodes } = currencyEvidence(src);

  // An ISO code is stronger than a symbol: "$" is used for USD, CAD and AUD.
  // Thus "CAD $1,000" is CAD, not a fabricated CAD/USD conflict.
  if (explicitCodes.size === 1) {
    const currency = [...explicitCodes][0]!;
    notes.push(`currency inferred from explicit ISO code as ${currency}`);
    return currency;
  }
  if (explicitCodes.size > 1) {
    notes.push(`conflicting explicit currency codes (${[...explicitCodes].join(", ")}) — marked UNKNOWN`);
    return null;
  }
  if (symbolCodes.size === 1) {
    const currency = [...symbolCodes][0]!;
    notes.push(`currency inferred from amount symbol as ${currency}`);
    return currency;
  }
  if (symbolCodes.size > 1) {
    notes.push(`conflicting currency symbols (${[...symbolCodes].join(", ")}) — marked UNKNOWN`);
    return null;
  }
  notes.push("currency missing — marked UNKNOWN for human clarification");
  return null;
}

function pickAmount(
  src: RawInvoice,
  keys: string[],
  label: string,
  notes: string[]
): number | null {
  for (const k of keys) {
    if (!(k in src)) continue;
    const raw = src[k];
    const n = parseAmount(raw);
    if (n != null) {
      if (typeof raw === "string") notes.push(`${label} "${raw}" parsed as ${n}`);
      return round2(n);
    }
    if (raw != null && raw !== "") notes.push(`${label} value ${JSON.stringify(raw)} was unparseable`);
  }
  return null;
}

function normalizeDate(value: string | null, notes: string[]): string | null {
  if (!value) return null;
  const t = Date.parse(value);
  if (Number.isNaN(t)) {
    notes.push(`invoice_date "${value}" was unparseable`);
    return null;
  }
  return new Date(t).toISOString().slice(0, 10);
}

function normalizeLineItems(value: unknown, notes: string[]): LineItem[] {
  if (!Array.isArray(value)) return [];
  const items: LineItem[] = [];
  for (const entry of value) {
    if (typeof entry !== "object" || entry == null) continue;
    const e = entry as Record<string, unknown>;
    items.push({
      description: pickString(e, ["description", "desc", "name", "item"]) ?? "(no description)",
      quantity: parseAmount(e["quantity"] ?? e["qty"]),
      unit_price: parseAmount(e["unit_price"] ?? e["price"] ?? e["rate"]),
      amount: parseAmount(e["amount"] ?? e["total"] ?? e["line_total"]),
    });
  }
  if (items.length === 0 && value.length > 0) {
    notes.push("line_items present but none were parseable");
  }
  return items;
}

function round2(n: number): number {
  return Math.round(n * 100) / 100;
}
